name: Ktlint
on: [push]
jobs:
  Ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: musichin/ktlint-check@v1
        with:
          version: '0.42.1'
          warn: true # warn only

          # ktlint
          relative: true
          experimental: true
          reporter: |
            plain,output=ktlint_report.txt
            json,output=ktlint_report.json
          patterns: |
            **/**.kt
            !**/generated/**
