name: Ktlint
on: [push]
jobs:
  Ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: musichin/ktlint-check@v2
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: '0.42.1'
          warn: true # warn only

          # ktlint
          relative: true
          experimental: true
          reporter: |
            plain,output=ktlint_report.txt
            json,output=ktlint_report.json
          patterns: |
            **/**.kt
            !**/generated/**
          
